api.function <- function(...) NULL

# events
get.public.events <- function(ctx = get.github.context())
  api.get.request(ctx, c("events"))
get.repository.events <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "events"))
get.repository.issue.events <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", "events"))
# TODO I believe the documentation on http://developer.github.com/v3/activity/events/ is wrong for network.public.events, but in case it isn't...
get.network.public.events <- function(owner, ctx = get.github.context())
  api.get.request(ctx, c("networks", owner, "events"))
get.organization.public.events <- function(org, ctx = get.github.context())
  api.get.request(ctx, c("orgs", org, "events"))
get.user.received.events <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "received_events"))
get.user.public.received.events <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "received_events", "public"))
get.user.performed.events <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "events"))
get.user.public.performed.events <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "events", "public"))
get.my.organization.events <- function(org, ctx = get.github.context())
  api.get.request(ctx, c("users", ctx$user$login, "events", "orgs", org))

# notifications
get.my.notifications <- function(..., ctx=get.github.context())
  api.get.request(ctx, c("notifications"), params=list(...))
get.my.repository.notifications <- function(owner, repo, ..., ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "notifications"), params=list(...))
mark.my.notifications <- function(..., ctx = get.github.context())
  api.put.request(ctx, c("notifications"), expect.code=205, params=list(...))
mark.my.repository.notifications <- function(owner, repo, ..., ctx = get.github.context())
  api.put.request(ctx, c("repos", owner, repo, "notifications"), expect.code=205, params=list(...))
get.thread.notifications <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("notifications", "threads", id))
mark.thread.notifications <- function(id, ..., ctx = get.github.context())
  api.patch.request(ctx, c("notifications", "threads", id), expect.code=205, params=list(...))
get.thread.notifications.subscription <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("notifications", "threads", id, "subscription"))
set.thread.notifications.subscription <- function(id, ..., ctx = get.github.context())
  api.put.request(ctx, c("notifications", "threads", id, "subscription"), params=list(...))
unset.thread.notifications.subscription <- function(id, ctx = get.github.context())
  api.delete.request(ctx, c("notifications", "threads", id, "subscription"))

# starring
get.stargazers <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "stargazers"))
get.repositories.starred.by.user <- function(user, ..., ctx = get.github.context())
  api.get.request(ctx, c("users", user, "starred"), params=list(...))
get.repositories.starred.by.me <- function(..., ctx = get.github.context())
  api.get.request(ctx, c("user", "starred"), params=list(...))
is.repository.starred.by.me <- function(owner, repo, ctx = get.github.context())
  api.test.request(ctx, c("user", "starred", owner, repo))
star.repository <- function(owner, repo, ctx = get.github.context())
  api.put.request(ctx, c("user", "starred", owner, repo), expect.code=204)
unstar.repository <- function(owner, repo, ctx = get.github.context())
  api.delete.request(ctx, c("user", "starred", owner, repo), expect.code=204)

# watching
# NB http://developer.github.com/changes/2012-9-5-watcher-api/
get.watchers <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "subscribers"))
get.repositories.watched.by.user <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "subscriptions"))
get.repositories.watched.by.me <- function(ctx)
  api.get.request(ctx, c("user", "subscriptions"))
get.repository.subscription <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "subscription"))
set.repository.subscription <- function(owner, repo, ..., ctx = get.github.context())
  api.put.request(ctx, c("repos", owner, repo, "subscription"), params=list(...))
unset.repository.subscription <- function(owner, repo, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "subscription"))
