get.my.gists <- function(ctx = get.github.context())
  api.get.request   (ctx, c("gists"))
get.user.gists <- function(user, ctx = get.github.context())
  api.get.request   (ctx, c("users", user, "gists"))
get.gist <- function(id, version = NULL, ctx = get.github.context())
  api.get.request   (ctx, c("gists", id, version))
star.gist <- function(id, ctx = get.github.context())
  api.put.request   (ctx, c("gists", id, "star"), expect.code=204)
unstar.gist <- function(id, ctx = get.github.context())
  api.delete.request(ctx, c("gists", id, "star"))
is.starred <- function(id, ctx = get.github.context())
  api.test.request  (ctx, c("gists", id, "star"))
fork.gist <- function(id, ctx = get.github.context())
  api.post.request  (ctx, c("gists", id, "forks"))
delete.gist <- function(id, ctx = get.github.context())
  api.delete.request(ctx, c("gists", id))
create.gist <- function(content, ctx = get.github.context())
  api.post.request  (ctx, c("gists"), body=content)
update.gist <- function(id, content, ctx = get.github.context())
  api.patch.request (ctx, c("gists", id), body=content)

# comments
get.gist.comments <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("gists", id, "comments"))
get.gist.comment <- function(gist.id, comment.id, ctx = get.github.context())
  api.get.request(ctx, c("gists", gist.id, "comment", comment.id))
create.gist.comment <- function(gist.id, content, config=add_headers(Accept='application/vnd.github.v3.text+json'), ctx = get.github.context())
  api.post.request(ctx, c("gists", gist.id, "comments"), body=content, config=config)
update.gist.comment <- function(gist.id, comment.id, content, config=add_headers(Accept='application/vnd.github.v3.text+json'), ctx = get.github.context())
  api.patch.request(ctx, c("gists", gist.id, "comments", comment.id), body=content, config=config)
delete.gist.comment <- function(gist.id, comment.id, ctx = get.github.context())
  api.patch.request(ctx, c("gists", gist.id, "comments", comment.id))
