get.my.gists <- api.function(function(ctx)
  api.get.request   (ctx, c("gists")))
get.user.gists <- api.function(function(ctx, user)
  api.get.request   (ctx, c("users", user, "gists")))
get.gist <- api.function(function(ctx, id, version = NULL)
  api.get.request   (ctx, c("gists", id, version)))
star.gist <- api.function(function(ctx, id)
  api.put.request   (ctx, c("gists", id, "star"), expect.code=204))
unstar.gist <- api.function(function(ctx, id)
  api.delete.request(ctx, c("gists", id, "star")))
is.starred <- api.function(function(ctx, id)
  api.test.request  (ctx, c("gists", id, "star")))
fork.gist <- api.function(function(ctx, id)
  api.post.request  (ctx, c("gists", id, "forks")))
delete.gist <- api.function(function(ctx, id)
  api.delete.request(ctx, c("gists", id)))
create.gist <- api.function(function(ctx, content)
  api.post.request  (ctx, c("gists"), body=content))
update.gist <- api.function(function(ctx, id, content)
  api.patch.request (ctx, c("gists", id), body=content))

# comments
get.gist.comments <- api.function(function(ctx, id)
  api.get.request(ctx, c("gists", id, "comments")))
get.gist.comment <- api.function(function(ctx, gist.id, comment.id)
  api.get.request(ctx, c("gists", gist.id, "comment", comment.id)))
create.gist.comment <- api.function(function(ctx, gist.id, content, config=add_headers(Accept='application/vnd.github.v3.text+json'))
  api.post.request(ctx, c("gists", gist.id, "comments"), body=content, config=config))
update.gist.comment <- api.function(function(ctx, gist.id, comment.id, content, config=add_headers(Accept='application/vnd.github.v3.text+json'))
  api.patch.request(ctx, c("gists", gist.id, "comments", comment.id), body=content, config=config))
delete.gist.comment <- api.function(function(ctx, gist.id, comment.id)
  api.patch.request(ctx, c("gists", gist.id, "comments", comment.id)))
