get.all.my.issues <- function(..., ctx = get.github.context())
  api.get.request(ctx, c("issues"), params=list(...))
get.my.issues <- function(..., ctx = get.github.context())
  api.get.request(ctx, c("user", "issues"), params=list(...))
get.organization.issues <- function(org, ..., ctx = get.github.context())
  api.get.request(ctx, c("orgs", org, "issues"), params=list(...))
get.repository.issues <- function(owner, repo, ..., ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues"), params=list(...))

create.issue <- function(owner, repo, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "issues"), body=content)
modify.issue <- function(owner, repo, number, content, ctx = get.github.context())
  api.patch.request(ctx, c("repos", owner, repo, "issues", number), body=content)

# assignees
get.assignees <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "assignees"))
is.assignee <- function(owner, repo, assignee, ctx = get.github.context())
  api.test.request(ctx, c("repos", owner, repo, "assignees", assignee))

# comments
get.issue.comments <- function(owner, repo, number, ..., ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", number, "comments"), params=list(...))
get.issue.comment <- function(owner, repo, issue.number, comment.number, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments", comment.number))
create.issue.comment <- function(owner, repo, issue.number, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments"), body=content)
modify.issue.comment <- function(owner, repo, issue.number, comment.number, content, ctx = get.github.context())
  api.patch.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments", comment.number), body=content)
delete.issue.comment <- function(owner, repo, issue.number, comment.number, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments", comment.number))

# events
get.issue.events <- function(owner, repo, issue.number, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", issue.number, "events"))
repository.issue.events <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", "events"))
repository.issue.event  <- function(owner, repo, event.number, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", "events", event.number))

# labels
get.repository.labels <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "labels"))
get.repository.label <- function(owner, repo, name, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "labels", name))
create.repository.label <- function(owner, repo, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "labels"), body=content)
modify.repository.label <- function(owner, repo, name, content, ctx = get.github.context())
  api.patch.request(ctx, c("repos", owner, repo, "labels", name), body=content)
delete.repository.label <- function(owner, repo, name, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "labels", name))

get.issue.labels <- function(owner, repo, issue.number, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"))
add.issue.labels <- function(owner, repo, issue.number, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"), expect.code=200, body=content)
delete.issue.labels <- function(owner, repo, issue.number, name, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels", name))
replace.issue.labels <- function(owner, repo, issue.number, content, ctx = get.github.context())
  api.put.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"), body=content)
delete.all.issue.labels <- function(owner, repo, issue.number, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"), body=content)
get.milestone.labels <- function(owner, repo, milestone.number, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "milestones", milestone.number, "labels"))

# milestones

get.milestones <- function(owner, repo, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "milestones"))
get.milestone <- function(owner, repo, milestone.number, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "milestones", milestone.number))
create.milestone <- function(owner, repo, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "milestones"), body=content)
modify.milestone <- function(owner, repo, milestone.number, content, ctx = get.github.context())
  api.patch.request(ctx, c("repos", owner, repo, "milestones", milestone.number), body=content)
delete.milestone <- function(owner, repo, milestone.number, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "milestones", milestone.number))
