get.all.my.issues <- api.function(function(ctx, ...)
  api.get.request(ctx, c("issues"), params=.rest(...)))
get.my.issues <- api.function(function(ctx, ...)
  api.get.request(ctx, c("user", "issues"), params=.rest(...)))
get.organization.issues <- api.function(function(ctx, org, ...)
  api.get.request(ctx, c("orgs", org, "issues"), params=.rest(...)))
get.repository.issues <- api.function(function(ctx, owner, repo, ...)
  api.get.request(ctx, c("repos", owner, repo, "issues"), params=.rest(...)))

create.issue <- api.function(function(ctx, owner, repo, content)
  api.post.request(ctx, c("repos", owner, repo, "issues"), body=content))
update.issue <- api.function(function(ctx, owner, repo, number, content)
  api.patch.request(ctx, c("repos", owner, repo, "issues", number), body=content))

# assignees
get.assignees <- api.function(function(ctx, owner, repo)
  api.get.request(ctx, c("repos", owner, repo, "assignees")))
is.assignee <- api.function(function(ctx, owner, repo, assignee)
  api.test.request(ctx, c("repos", owner, repo, "assignees", assignee)))

# comments
get.issue.comments <- api.function(function(ctx, owner, repo, number, ...)
  api.get.request(ctx, c("repos", owner, repo, "issues", number, "comments"), params=.rest(...)))
get.issue.comment <- api.function(function(ctx, owner, repo, issue.number, comment.number)
  api.get.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments", comment.number)))
create.issue.comment <- api.function(function(ctx, owner, repo, issue.number, content)
  api.post.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments"), body=content))
update.issue.comment <- api.function(function(ctx, owner, repo, issue.number, comment.number, content)
  api.patch.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments", comment.number), body=content))
delete.issue.comment <- api.function(function(ctx, owner, repo, issue.number, comment.number)
  api.delete.request(ctx, c("repos", owner, repo, "issues", issue.number, "comments", comment.number)))

# events
get.issue.events <- api.function(function(ctx, owner, repo, issue.number)
  api.get.request(ctx, c("repos", owner, repo, "issues", issue.number, "events")))
repository.issue.events <- api.function(function(ctx, owner, repo)
  api.get.request(ctx, c("repos", owner, repo, "issues", "events")))
repository.issue.event  <- api.function(function(ctx, owner, repo, event.number)
  api.get.request(ctx, c("repos", owner, repo, "issues", "events", event.number)))

# labels
get.repository.labels <- api.function(function(ctx, owner, repo)
  api.get.request(ctx, c("repos", owner, repo, "labels")))
get.repository.label <- api.function(function(ctx, owner, repo, name)
  api.get.request(ctx, c("repos", owner, repo, "labels", name)))
create.repository.label <- api.function(function(ctx, owner, repo, content)
  api.post.request(ctx, c("repos", owner, repo, "labels"), body=content))
update.repository.label <- api.function(function(ctx, owner, repo, name, content)
  api.patch.request(ctx, c("repos", owner, repo, "labels", name), body=content))
delete.repository.label <- api.function(function(ctx, owner, repo, name)
  api.delete.request(ctx, c("repos", owner, repo, "labels", name)))

get.issue.labels <- api.function(function(ctx, owner, repo, issue.number)
  api.get.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels")))
add.issue.labels <- api.function(function(ctx, owner, repo, issue.number, content)
  api.post.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"), expect.code=200, body=content))
delete.issue.labels <- api.function(function(ctx, owner, repo, issue.number, name)
  api.delete.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels", name)))
replace.issue.labels <- api.function(function(ctx, owner, repo, issue.number, content)
  api.put.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"), body=content))
delete.all.issue.labels <- api.function(function(ctx, owner, repo, issue.number)
  api.delete.request(ctx, c("repos", owner, repo, "issues", issue.number, "labels"), body=content))
get.milestone.labels <- api.function(function(ctx, owner, repo, milestone.number)
  api.get.request(ctx, c("repos", owner, repo, "milestones", milestone.number, "labels")))

# milestones

get.milestones <- api.function(function(ctx, owner, repo)
  api.get.request(ctx, c("repos", owner, repo, "milestones")))
get.milestone <- api.function(function(ctx, owner, repo, milestone.number)
  api.get.request(ctx, c("repos", owner, repo, "milestones", milestone.number)))
create.milestone <- api.function(function(ctx, owner, repo, content)
  api.post.request(ctx, c("repos", owner, repo, "milestones"), body=content))
update.milestone <- api.function(function(ctx, owner, repo, milestone.number, content)
  api.patch.request(ctx, c("repos", owner, repo, "milestones", milestone.number), body=content))
delete.milestone <- api.function(function(ctx, owner, repo, milestone.number)
  api.delete.request(ctx, c("repos", owner, repo, "milestones", milestone.number)))
