get.user.organizations <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "orgs"))
get.my.organizations <- function(ctx = get.github.context())
  api.get.request(ctx, c("user", "orgs"))
get.organization <- function(org, ctx = get.github.context())
  api.get.request(ctx, c("orgs", org))
update.organization <- function(org, content, ctx = get.github.context())
  api.patch.request(ctx, c("orgs", org), body=content)

# members
get.organization.members <- function(org, ctx = get.github.context())
  api.get.request(ctx, c("orgs", org, "members"))
is.member.of.organization <- function(org, user, ctx = get.github.context())
  api.test.request(ctx, c("orgs", org, "members", user))
delete.member.from.organization <- function(org, user, ctx = get.github.context())
  api.delete.request(ctx, c("orgs", org, "members", user))
get.organization.public.members <- function(org, ctx = get.github.context())
  api.get.request(ctx, c("orgs", org, "public_members"))
is.public.member.of.organization <- function(org, user, ctx = get.github.context())
  api.test.request(ctx, c("orgs", org, "public_members", user))
publicize.member.of.organization <- function(org, user, ctx = get.github.context())
  api.put.request(ctx, c("orgs", org, "public_members", user), expect.code=204)
conceal.member.of.organization <- function(org, user, ctx = get.github.context())
  api.delete.request(ctx, c("orgs", org, "public_members", user))

# teams
get.organization.teams <- function(org, ctx = get.github.context())
  api.get.request(ctx, c("orgs", org, "teams"))
get.team <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("teams", id))
create.team <- function(org, content, ctx = get.github.context())
  api.get.request(ctx, c("orgs", org, "teams"), body=content)
update.team <- function(id, content, ctx = get.github.context())
  api.patch.request(ctx, c("teams", id), body=content)
delete.team <- function(id, ctx = get.github.context())
  api.delete.request(ctx, c("teams", id))
get.team.members <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("teams", id, "members"))
is.member.in.team <- function(id, user, ctx = get.github.context())
  api.test.request(ctx, c("teams", id, "members", user))
add.member.to.team <- function(id, user, ctx = get.github.context())
  api.put.request(ctx, c("teams", id, "members", user), expect.code=204)
delete.member.from.team <- function(id, user, ctx = get.github.context())
  api.delete.request(ctx, c("teams", id, "members", user))
get.team.repositories <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("teams", id, "repos"))
is.repository.in.team <- function(id, owner, repo, ctx = get.github.context())
  api.test.request(ctx, c("teams", id, "repos", owner, repo))
add.repository.to.team <- function(id, owner, repo, ctx = get.github.context())
  api.put.request(ctx, c("teams", id, "repos", owner, repo), expect.code=204)
delete.repository.from.team <- function(id, owner, repo, ctx = get.github.context())
  api.delete.request(ctx, c("teams", id, "repos", owner, repo))

