get.user.organizations <- api.function(function(ctx, user)
  api.get.request(ctx, c("users", user, "orgs")))
get.my.organizations <- api.function(function(ctx)
  api.get.request(ctx, c("user", "orgs")))
get.organization <- api.function(function(ctx, org)
  api.get.request(ctx, c("orgs", org)))
update.organization <- api.function(function(ctx, org, content)
  api.patch.request(ctx, c("orgs", org), body=content))

# members
get.organization.members <- api.function(function(ctx, org)
  api.get.request(ctx, c("orgs", org, "members")))
is.member.of.organization <- api.function(function(ctx, org, user)
  api.test.request(ctx, c("orgs", org, "members", user)))
delete.member.from.organization <- api.function(function(ctx, org, user)
  api.delete.request(ctx, c("orgs", org, "members", user)))
get.organization.public.members <- api.function(function(ctx, org)
  api.get.request(ctx, c("orgs", org, "public_members")))
is.public.member.of.organization <- api.function(function(ctx, org, user)
  api.test.request(ctx, c("orgs", org, "public_members", user)))
publicize.member.of.organization <- api.function(function(ctx, org, user)
  api.put.request(ctx, c("orgs", org, "public_members", user), expect.code=204))
conceal.member.of.organization <- api.function(function(ctx, org, user)
  api.delete.request(ctx, c("orgs", org, "public_members", user)))

# teams
get.organization.teams <- api.function(function(ctx, org)
  api.get.request(ctx, c("orgs", org, "teams")))
get.team <- api.function(function(ctx, id)
  api.get.request(ctx, c("teams", id)))
create.team <- api.function(function(ctx, org, content)
  api.get.request(ctx, c("orgs", org, "teams"), body=content))
update.team <- api.function(function(ctx, id, content)
  api.patch.request(ctx, c("teams", id), body=content))
delete.team <- api.function(function(ctx, id)
  api.delete.request(ctx, c("teams", id)))
get.team.members <- api.function(function(ctx, id)
  api.get.request(ctx, c("teams", id, "members")))
is.member.in.team <- api.function(function(ctx, id, user)
  api.test.request(ctx, c("teams", id, "members", user)))
add.member.to.team <- api.function(function(ctx, id, user)
  api.put.request(ctx, c("teams", id, "members", user), expect.code=204))
delete.member.from.team <- api.function(function(ctx, id, user)
  api.delete.request(ctx, c("teams", id, "members", user)))
get.team.repositories <- api.function(function(ctx, id)
  api.get.request(ctx, c("teams", id, "repos")))
is.repository.in.team <- api.function(function(ctx, id, owner, repo)
  api.test.request(ctx, c("teams", id, "repos", owner, repo)))
add.repository.to.team <- api.function(function(ctx, id, owner, repo)
  api.put.request(ctx, c("teams", id, "repos", owner, repo), expect.code=204))
delete.repository.from.team <- api.function(function(ctx, id, owner, repo)
  api.delete.request(ctx, c("teams", id, "repos", owner, repo)))

