get.pull.requests <- function(owner, repo, ..., ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls"), params=list(...))
get.pull.request <- function(owner, repo, id, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls", id))
create.pull.request <- function(owner, repo, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "pulls"), body=content)
update.pull.request <- function(owner, repo, id, content, ctx = get.github.context())
  api.patch.request(ctx, c("repos", owner, repo, "pulls", id), body=content)
get.pull.request.commits <- function(owner, repo, id, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls", id, "commits"))
get.pull.request.files <- function(owner, repo, id, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls", id, "files"))
is.pull.request.merged <- function(owner, repo, id, ctx = get.github.context())
  api.test.request(ctx, c("repos", owner, repo, "pulls", id, "merge"))
merge.pull.request <- function(owner, repo, id, ..., ctx = get.github.context())
  api.put.request(ctx, c("repos", owner, repo, "pulls", id, "merge"), params=list(...))

# comments
get.pull.request.comments <- function(owner, repo, id, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls", id, "comments"))
get.pull.requests.comments <- function(owner, repo, ..., ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls", "comments"), params=list(...))
get.pull.requests.comment <- function(owner, repo, comment.id, ctx = get.github.context())
  api.get.request(ctx, c("repos", owner, repo, "pulls", "comments", comment.id))
create.pull.request.comment <- function(owner, repo, pull.id, content, ctx = get.github.context())
  api.post.request(ctx, c("repos", owner, repo, "pulls", pull.id, "comments"), body=content)
update.pull.request.comment <- function(owner, repo, pull.id, content, ctx = get.github.context())
  api.patch.request(ctx, c("repos", owner, repo, "pulls", pull.id, "comments"), body=content)
delete.pull.request.comment <- function(owner, repo, comment.id, ctx = get.github.context())
  api.delete.request(ctx, c("repos", owner, repo, "pulls", "comments", comment.id))
