get.pull.requests <- api.function(function(ctx, owner, repo, ...)
  api.get.request(ctx, c("repos", owner, repo, "pulls"), params=.rest(...)))
get.pull.request <- api.function(function(ctx, owner, repo, id)
  api.get.request(ctx, c("repos", owner, repo, "pulls", id)))
create.pull.request <- api.function(function(ctx, owner, repo, content)
  api.post.request(ctx, c("repos", owner, repo, "pulls"), body=content))
update.pull.request <- api.function(function(ctx, owner, repo, id, content)
  api.patch.request(ctx, c("repos", owner, repo, "pulls", id), body=content))
get.pull.request.commits <- api.function(function(ctx, owner, repo, id)
  api.get.request(ctx, c("repos", owner, repo, "pulls", id, "commits")))
get.pull.request.files <- api.function(function(ctx, owner, repo, id)
  api.get.request(ctx, c("repos", owner, repo, "pulls", id, "files")))
is.pull.request.merged <- api.function(function(ctx, owner, repo, id)
  api.test.request(ctx, c("repos", owner, repo, "pulls", id, "merge")))
merge.pull.request <- api.function(function(ctx, owner, repo, id, ...)
  api.put.request(ctx, c("repos", owner, repo, "pulls", id, "merge"), params=.rest(...)))

# comments
get.pull.request.comments <- api.function(function(ctx, owner, repo, id)
  api.get.request(ctx, c("repos", owner, repo, "pulls", id, "comments")))
get.pull.requests.comments <- api.function(function(ctx, owner, repo, ...)
  api.get.request(ctx, c("repos", owner, repo, "pulls", "comments"), params=.rest(...)))
get.pull.requests.comment <- api.function(function(ctx, owner, repo, comment.id)
  api.get.request(ctx, c("repos", owner, repo, "pulls", "comments", comment.id)))
create.pull.request.comment <- api.function(function(ctx, owner, repo, pull.id, content)
  api.post.request(ctx, c("repos", owner, repo, "pulls", pull.id, "comments"), body=content))
update.pull.request.comment <- api.function(function(ctx, owner, repo, pull.id, content)
  api.patch.request(ctx, c("repos", owner, repo, "pulls", pull.id, "comments"), body=content))
delete.pull.request.comment <- api.function(function(ctx, owner, repo, comment.id)
  api.delete.request(ctx, c("repos", owner, repo, "pulls", "comments", comment.id)))
