get.user <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user))
get.myself <- function(ctx = get.github.context())
  api.get.request(ctx, "user")
modify.myself <- function(content, ctx = get.github.context())
  api.patch.request(ctx, "user", body = content)
get.users <- function(..., ctx = get.github.context())
  api.get.request(ctx, c("users"), params=list(...))

# emails
get.my.emails <- function(ctx = get.github.context())
  api.get.request(ctx, c("user", "emails"))
add.emails <- function(content, ctx = get.github.context())
  api.post.request(ctx, c("user", "emails"), body=content)
delete.emails <- function(content, ctx = get.github.context())
  api.delete.request(ctx, c("user", "emails"))

# followers/following
get.user.followers <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "followers"))
get.my.followers <- function(ctx = get.github.context())
  api.get.request(ctx, c("user", "followers"))
get.user.following <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "following"))
get.my.following <- function(ctx = get.github.context())
  api.get.request(ctx, c("user", "following"))
am.following.user <- function(user, ctx = get.github.context())
  api.test.request(ctx, c("user", "following", user))
follow.user <- function(user, ctx = get.github.context())
  api.put.request(ctx, c("user", "following", user), expect.code=204)
unfollow.user <- function(user, ctx = get.github.context())
  api.delete.request(ctx, c("user", "following", user), expect.code=204)

# keys
get.user.keys <- function(user, ctx = get.github.context())
  api.get.request(ctx, c("users", user, "keys"))
get.my.keys <- function(ctx = get.github.context())
  api.get.request(ctx, c("user", "keys"))
get.key <- function(id, ctx = get.github.context())
  api.get.request(ctx, c("user", "keys", id))
create.key <- function(content, ctx = get.github.context())
  api.post.request(ctx, c("user", "keys"), body=content)
modify.key <- function(id, content, ctx = get.github.context())
  api.patch.request(ctx, c("user", "keys", id), body=content)
delete.key <- function(id, ctx = get.github.context())
  api.delete.request(ctx, c("user", "keys"))
