get.user <- api.function(function(ctx, user)
  api.get.request(ctx, c("users", user)))
get.myself <- api.function(function(ctx)
  api.get.request(ctx, "user"))
update.myself <- api.function(function(ctx, content)
  api.patch.request(ctx, "user", body=content))
get.users <- api.function(function(ctx, ...)
  api.get.request(ctx, c("users"), params=.rest(...)))

# emails
get.my.emails <- api.function(function(ctx)
  api.get.request(ctx, c("user", "emails")))
add.emails <- api.function(function(ctx, content)
  api.post.request(ctx, c("user", "emails"), body=content))
delete.emails <- api.function(function(ctx, content)
  api.delete.request(ctx, c("user", "emails"), body=content))

# followers/following
get.user.followers <- api.function(function(ctx, user)
  api.get.request(ctx, c("users", user, "followers")))
get.my.followers <- api.function(function(ctx)
  api.get.request(ctx, c("user", "followers")))
get.user.following <- api.function(function(ctx, user)
  api.get.request(ctx, c("users", user, "following")))
get.my.following <- api.function(function(ctx)
  api.get.request(ctx, c("user", "following")))
am.following.user <- api.function(function(ctx, user)
  api.test.request(ctx, c("user", "following", user)))
follow.user <- api.function(function(ctx, user)
  api.put.request(ctx, c("user", "following", user), expect.code=204))
unfollow.user <- api.function(function(ctx, user)
  api.delete.request(ctx, c("user", "following", user), expect.code=204))

# keys
get.user.keys <- api.function(function(ctx, user)
  api.get.request(ctx, c("users", user, "keys")))
get.my.keys <- api.function(function(ctx)
  api.get.request(ctx, c("user", "keys")))
get.key <- api.function(function(ctx, id)
  api.get.request(ctx, c("user", "keys", id)))
create.key <- api.function(function(ctx, content)
  api.post.request(ctx, c("user", "keys"), body=content))
update.key <- api.function(function(ctx, id, content)
  api.patch.request(ctx, c("user", "keys", id), body=content))
delete.key <- api.function(function(ctx, id)
  api.delete.request(ctx, c("user", "keys"), body=content))
